= Краткое руководство по миграции на Firebird 4.0

toc::[]

[preface]
== Введение

Эта статья предназначена прежде всего для тех кто планирует в ближайшем будущем обновить СУБД Firebird до версии 4.0.
Я знаю что многие администраторы всё ещё используют Firebird 2.5, но планируют обновиться до версии 4.0 прежде всего из-за наличия в ней встроенной репликации.
Именно поэтому я буду описывать процесс миграции как с Firebird 2.5, так и Firebird 3.0.

== Ручная установка Firebird 4.0 в Windows

Я буду описывать процесс установки из zip архива.
Даже если вы устанавливаете Firebird из специального инсталяционного пакета, вам всё равно может потребоваться изменить некоторые настройки после установки.
Кроме того, ручная установка позволяет установить несколько версий Firebird на одной машине.

Скачайте архив соответствующей разрядности и распакуйте его в директорию, в которой будет размещён сервер Firebird.
Далее необходимо создать пользователя SYSDBA.
Для тех администраторов которые мигрируют с Firebird 3.0 это операция не нова.
В Firebird 2.5 и ранее после установки пользователь SYSDBA существовал всегда и имел пароль по умолчанию _masterke_, который надо было сразу же менять.

=== Инициализация SYSDBA

Начиная с Firebird 3.0 пользователь SYSDBA не инициализирован по умолчанию (для плагина управления пользователями SRP), поэтому необходимо явно создать пользователя и указать ему пароль.
Это можно сделать двумя способами:
с использованием консольного инструмента для выполнения интерактивных запросов _isql.exe_ и консольного инструмента для управления базой данных безопасности _gsec.exe_.

[NOTE]
.Замечание
====
В зависимости от размещения Firebird эти утилиты могут потребовать запуска с привилегиями администратора.
====

==== Инициализация SYSDBA с помощью ISQL

Запустите инструмент для выполнения интерактивных запросов _isql.exe_.
Соединитесь с базой данных безопасности в режиме встроенного сервера, указав при этом пользователя SYSDBA без пароля.
Пользователя SYSDBA ещё не существует в базе данных безопасности, но в embedded режиме пользователь и его пароль не проверяется, и Firebird доверяет любому указанному имени пользователя.
Выполите SQL запрос для создания пользователя SYSDBA:

[listing,subs=+quotes]
----
CREATE USER SYSDBA PASSWORD '<password>';
----

Пользователь SYSDBA инициализирован, можно выходить из интерактивного режима.

[example]
.Инициализация SYSDBA через ISQL
====
[listing,subs=+quotes]
----
isql c:\Firebird\3.0>isql
Use CONNECT or CREATE DATABASE to specify a database
SQL> connect security.db user SYSDBA; Database: security.db, User: SYSDBA
SQL> CREATE USER SYSDBA PASSWORD 'm8ku234pp';
SQL> exit;

c:\Firebird\3.0>
----
====

==== Инициализация SYSDBA с помощью GSEC

Запустите _gsec.exe_ указав пользователя SYSDBA и базу данных `security.db`.
Выполите команду для добавления пользователя SYSDBA:

----
add SYSDBA -pw <password>
----

[example]
.Инициализация SYSDBA через GSEC
====
[listing,subs=+quotes]
----
c:\Firebird\3.0>gsec -user SYSDBA -database security.db
* gsec is deprecated, will be removed soon *

GSEC> add SYSDBA -pw m8ku234pp
GSEC> quit

c:\Firebird\3.0>
----
====

[WARNING]
.Предупреждение
====
Инструмент _gsec.exe_ является устаревшим, многие возможности доступные через SQL не доступны в нём.
====

=== Конфигурация

Перед тем как установить и запустить Firebird как службу необходимо выбрать режим работы сервера.

==== Режим сервера

По-умолчанию Firebird будет стартовать в режиме SuperServer.
Если вы хотите чтобы сервер запускался в другой архитектуре, то необходимо изменить значение параметра _ServerMode_ в `firebird.conf`.
Раскомментируйте его (удалите решётку) и установите нужный режим: Super, SuperClassic или Classic.

[listing,subs=+quotes]
----
ServerMode = Classic
----

==== Авторизация с предыдущих версий клиента Firebird

Авторизация с предыдущих версий клиента Firebird В Firebird 4.0 по умолчанию используется безопасная парольная аутентификация (SRP).
Клиенты Firebird 2.5 и более ранние версии использовали традиционную аутентификацию (Legacy_Auth), которая отключена в Firebird 4.0 по-умолчанию, поскольку не является безопасной.

Для поддержки традиционной аутентификации необходимо изменить следующие параметры _AuthServer_, _UserManager_ и _WireCrypt_.

[example]
.Включение авторизации с предыдущих версий клиента Firebird
====
[listing,subs=+quotes]
----
AuthServer = Srp256, Srp, Legacy_Auth
UserManager = Srp, Legacy_UserManager
WireCrypt = Enabled
----
====

[NOTE]
====
Если вам не нужна поддержка безопасной парольной аутентификации (SRP), удалите из AuthServer плагины Srp256 и Srp; из AuthServer — Legacy_UserManager, а WireCrypt можете изменить на Disabled.
====

После вышеперечисленных манипуляций у нас будет активно два менеджера пользователей, по умолчанию активный тот что первый в списке UserManager.

[IMPORTANT]
.Важно
====
Одноименные пользователи в разных менеджерах пользователей — это разные пользователи.
====

Ранее мы уже создали SYSDBA в менеджере пользователей SRP.
В Legacy_UserManager SYSDBA уже существует, причём со стандартным паролем _masterkey_, который необходимо изменить.
Сделаем это c использованием инструмента isql.
В операторе `ALTER USER` необходимо обязательно указать менеджер пользователей Legacy_UserManager.

[example]
.Изменение пароля SYSDBA в Legacy_UserManager
====
[listing,subs=+quotes]
----
c:\Firebird\4.0>isql
Use CONNECT or CREATE DATABASE to specify a database
SQL> connect security.db user sysdba;
Database: security.db, User: SYSDBA
SQL> ALTER USER SYSDBA SET PASSWORD 'er34gfde' USING PLUGIN Legacy_UserManager;
SQL> exit;

c:\Firebird\4.0>
----
====

==== Установка часового пояса сервера

В Firebird 4.0 введены новые типы даты и времени с поддержкой часовых поясов.

Даже если вы не собираетесь в ближайшее время использовать типы с часовыми поясами, то необходимо учитывать, что выражения CURRENT_TIMESTAMP и CURRENT_TIME теперь возвращают типы данных с часовыми поясами.
Существует режим совместимости, который позволяет преобразовать типы с часовыми поясами в типы без часовых поясов.
Однако такое преобразование может работать неверно, если часовой пояс сервера выставлен неправильно.

Обычно часовой пояс сеанса задаётся на стороне клиента.
Если часовой пояс на стороне клиента не выставлен, то по умолчанию используется часовой пояс операционной системы.
Вы также можете выставить часовой пояс по умолчанию с помощью параметра конфигурации `DefaultTimeZone`.

[listing,subs=+quotes]
----
DefaultTimeZone = Europe/Moscow
----

==== Одновременный запуск нескольких Firebird

Для одновременного запуск нескольких Firebird, необходимо развести их по разным портам tcp (если конечно слушатель запущен в режиме прослушивания TCP/IP).
Для этого необходимо изменить в `firebird.conf` параметр _RemoteServicePort_.
Например, если у вас уже есть один сервер который слушает порт 3050, то необходимо установить любой другой свободный порт, например 3051. В этом случае в строке подключения необходимо будет указывать новый порт.

[listing,subs=+quotes]
----
RemoteServicePort = 3051
----

Если необходимо обеспечить также одновременную работоспособность по локальному протоколу XNET и через именованные каналы WNET, то необходимо так же изменить параметры _IpcName_ и _RemotePipeName_.
Однако стоит учесть, что эти параметры придётся изменять и на стороне клиента через DPB.

=== Установка и запуск Firebird как службы

Утилита _instsvc.exe_ записывает, удаляет или меняет информацию о запуске сервера в базе сервисов операционной системы.
Кроме того, она позволяет управлять запуском и остановкой сервиса.

Если запустить её без параметров, то будет выведена справка по командам и параметрам.

[listing,subs=+quotes]
----
instsvc
Usage:
  instsvc i[nstall]
                    [ -a[uto]* | -d[emand] ]
                    [ -g[uardian] ]
                    [ -l[ogin] username [password] ]
                    [ -n[ame] instance ]
                    [ -i[nteractive] ]

          sta[rt]   [ -b[oostpriority] ]
                    [ -n[ame] instance ]
          sto[p]    [ -n[ame] instance ]
          q[uery]
          r[emove]  [ -n[ame] instance ]


  '*' denotes the default values
  '-z' can be used with any other option, prints version
  'username' refers by default to a local account on this machine.
  Use the format 'domain\username' or 'server\username' if appropriate.
----

Для установки сервиса необходимо ввести команду

[listing,subs=+quotes]
----
instsvc install
----

В этом случае Firebird будет установлен в качестве службы с именем "Firebird Server – DefaultInstance".
Эта служба будет запускаться автоматически при старте ОС, под учётной записью LocalSystem, предназначенной для служб.

Если необходимо чтобы было установлено несколько экземпляров Firebird работающих как службы, то необходимо задать им разные имена с помощью переключателя -n

[listing,subs=+quotes]
----
instsvc install -n fb40
----

Для запуска службы воспользуйтесь командой

[listing,subs=+quotes]
----
instsvc start
----

Если служба была установлена с именем отличным от умолчательного, то необходимо воспользоваться переключателем -n

[listing,subs=+quotes]
----
instsvc start -n fb40
----

Для остановки службы воспользуйтесь командой

[listing,subs=+quotes]
----
instsvc stop
----

Если служба была установлена с именем отличным от умолчательного, то необходимо воспользоваться переключателем -n

[listing,subs=+quotes]
----
instsvc stop -n fb40
----

Для удаления сервиса необходимо ввести команду

[listing,subs=+quotes]
----
instsvc remove
----

Если служба была установлена с именем отличным от умолчательного, то необходимо воспользоваться переключателем -n

[listing,subs=+quotes]
----
instsvc remove -n fb40
----

Для просмотра всех служб Firebird установленных в системе воспользуйтесь командой

[listing,subs=+quotes]
----
instsvc query
----

[listing,subs=+quotes]
----
Firebird Server - fb30 IS installed.
  Status  : running
  Path    : C:\Firebird\3.0\firebird.exe -s fb30
  Startup : automatic
  Run as  : LocalSystem

Firebird Server - fb40 IS installed.
  Status  : running
  Path    : C:\Firebird\4.0\firebird.exe -s fb40
  Startup : automatic
  Run as  : LocalSystem
----

==== Использование install_service.bat и uninstall_service.bat

Для упрощения процедуру установки и удаления служб в ZIP архиве в комплекте с Firebird поставляются два BAT файла: `install_service.bat` и `uninstall_service.bat`.

В этом случае процедура установки Firebird в качестве сервиса выглядит следующим образом

[listing,subs=+quotes]
----
install_service.bat
----

В этом случае процедура удаления службы Firebird выглядит следующим образом

[listing,subs=+quotes]
----
uninstall_service.bat
----

Если необходимо задать службе имя отличное от умолчательного, то указываем это имя в качестве аргумента

[listing,subs=+quotes]
----
install_service.bat fb40
----

Если служба была установлена с именем отличным от умолчательного, то указываем это имя в качестве аргумента

[listing,subs=+quotes]
----
uninstall_service.bat fb40
----

=== Установка клиента

Если речь идёт об установке только о клиентской части, то обязательно требуется файл `fbclient.dll`.
Клиент Firebird 4.0 обязательно требует наличие установленного Microsoft Runtime C++ 2015 соответствующей разрядности.
Если данная библиотека не установлено, то можно скопировать дополнительные библиотеки, которые поставляются в ZIP архиве под Windows `msvcp140.dll` и `vcruntime140.dll`.

Желательно, чтобы рядом с `fbclient.dll` был расположен файл сообщений `firebird.msg`.
Большинство сообщений об ошибках уже содержатся в `fbclient.dll`, однако если вы собираетесь пользоваться консольными утилитами файл `firebird.msg` обязательно должен присутствовать.

В отличие от Firebird 2.5 и Firebird 3.0 клиентской библиотеки так же требуются файлы ICU (`icudt63.dll`, `icuin63.dll`, `icuuc63.dll` и `icudt63l.dat`).
Ранее ICU библиотека требовалась только серверу.
Теперь она также требуется и клиентской части если вы собираетесь работать с типами данных `TIMESTAMP WITH TIME ZONE` и `TIME WITH TIME ZONE`.

Если требуется сжатие трафика при работе по TCP/IP, то потребуется так же библиотека `zlib1.dll`.

Вам может потребоваться библиотека `plugins/chacha.dll` если вы собираетесь использовать плагин шифрования трафика ChaCha.

Для того чтобы клиентское приложение могло загрузить библиотеку `fbclient.dll` она должна располагаться либо рядом с приложением, либо в одной из директорий в которой производится поиск, например добавленной в `PATH` или системной директории для размещения общедоступных библиотек (`system32` или `SysWOW64`).

[IMPORTANT]
.Важно
====
Размещение клиентской библиотеки в `PATH` может помешать другим приложениям, которым требуется клиентская библиотека другой версии или другого сервера.
Поэтому, если предполагается, что приложение должно работать независимо от других приложений с конкретной версией клиента, то файлы клиента требуется разместить в папке приложения, и не прописывать этот путь в `PATH`.
====

Для развёртывания клиентской библиотеки Firebird в системном каталоге Windows воспользуйтесь командой

[listing,subs=+quotes]
----
instclient install fbclient
----

[IMPORTANT]
.Важно
====
Утилита instclient не копирует в системный каталог никаких файлов кроме `fbclient.dll`.
====

=== Установка embedded версии

Embedded версия теперь требует большего количества файлов.
Минимальная структура файлов и каталогов для Firebird 4.0 embedded следующая:

* intl
- fbintl.conf
- fbintl.dll
* plugins
- engine13.dll
* firebird.conf
* icudt63l.dat
* fbclient.dll
* ib_util.dll
* icudt63.dll
* icuin63.dll
* icuuc63.dll
* msvcp140.dll
* vcruntime140.dll
* firebird.msg

При необходимости вы также можете скопировать исполняемые файлы утилит `fbsvcmgr.exe`, `fbtracemgr.exe`,
`gbak.exe`, `gfix.exe`, `gstat.exe`, `isql.exe`, `nbackup.exe`.

[NOTE]
.Замечание
====
Для тех кто мигрирует с Firebird 2.5 следует учитывать 2 момента:

* Вместо единой библиотеки `fbembed.dll` требуется несколько файлов, причём файл `fbclient.dll` переименовывать нельзя.
Компоненты доступа должны использовать в качестве точки входа именно библиотеку `fbclient.dll`.
Если это не возможно обеспечить сделайте копию файла `fbclient.dll` с именем `fbembed.dll`.
При этом файл `fbclient.dll` должен оставаться на месте, поскольку помимо клиентской функции он является диспетчером, то есть связующим звеном между различными компонентами сервера.

* В файле конфигурации `firebird.conf` следует изменить значение параметра `ServerMode` на `SuperClassic` или `Classic`
для того чтобы можно было подключаться к одной и той же базе данных из разных процессов (поведения Firebird 2.5 embedded по умолчанию).
====

== Преобразование базы данных к новому формату

Базы данных Firebird 4.0 имеют ODS 13.0. Для того, чтобы Firebird 4.0 мог работать с вашей базой данных её необходимо привести к родной ODS.
Обычно это осуществляется с помощью инструмента gbak.
Однако не торопитесь делать резервное копирование своей БД и её восстановление с новой ODS — сначала необходимо устранить возможные проблемы совместимости.


=== Список не совместимостей на уровне языка SQL

Проблемы совместимости языка SQL возможны как для объектов самой базы данных (PSQL процедуры и функции), так и в DSQL запросах, используемых в вашем приложении.

Я перечислю некоторые наиболее часто встречающиеся проблемы совместимости на уровне SQL которые вы можете исправить ещё до перехода на новую ODS.
Полный список несовместимостей вы можете прочитать в Release Notes 3.0 (для тех кто переходит с Firebird 2.5) и Release Notes 4.0 в главе "Compatibility Issues".

==== Новые зарезервированные слова

Проверьте вашу базу данных на наличие новых зарезервированных слов в идентификаторах, столбцах и переменных.
В первом SQL диалекте такие слова не могут применяться в принципе (надо будет переименовать), в третьем — могут применяться, но должны обрамляться двойными кавычками.
Список ключевых и зарезервированных слов вы можете найти в Release Notes 3.0 и 4.0 в главе "Reserved Words and Changes".
Ключевые слова могут применяться в качестве идентификаторов, хотя это и не желательно.

==== Имена столбцов в PSQL курсорах

Этот пункт актуален для тех кто переходит с Firebird 2.5. Все выходные столбцы в PSQL курсорах объявленных как `DECLARE CURSOR` должны иметь явное имя или псевдоним.
То же самое касается PSQL курсоров используемых как `FOR SELECT ... AS CURSOR <cursor name> DO
...`.

[example]
.Проблема с неименованными столбцами в курсорах
====
[listing,subs=+quotes]
----
create procedure sp_test
returns (n int)
as
  declare c cursor for (select 1 /* as a */ from rdb$database);
begin
  open c;
  fetch c into n;
  close c;
  suspend;
end
----

----
Statement failed, SQLSTATE = 42000
unsuccessful metadata update
-ALTER PROCEDURE SP_TEST failed
-Dynamic SQL Error
-SQL error code = -104
-Invalid command
-no column name specified for column number 1 in derived table C
----
====

==== Новые типы данных

В Firebird 4.0 введены новые типы данных:

[options="compact"]
- `TIMESTAMP WITH TIME ZONE`
- `TIME WITH TIME ZONE`
- `INT128`
- `NUMERIC(38, x)` и `DECIMAL(38, x)`
- `DECFLOAT(16)` и `DECFLOAT(34)`
+
Последние два типа не вызывают особых проблем, поскольку раньше вы их не использовали, и обычно выражения их не возвращают.

Некоторые выражения теперь могу возвращать типы `NUMERIC(38, x)`,  `DECIMAL(38, x)` и `INT128`.
О решении этой проблемы мы поговорим позже, поскольку на этапе изменения ODS они обычно не проявляются.

Выражения `CURRENT_TIMESTAMP` и `CURRENT_TIME` теперь возвращают типы `TIMESTAMP WITH TIME ZONE` и `TIME WITH TIME ZONE`.
Это может стать серьёзной проблемой.
Для старых клиентских библиотек и приложений вы можете установить режим совместимости типов, однако это не поможет внутри хранимых процедур, функций и триггеров.
Вам необходимо использовать выражения `LOCALTIMESTAMP` и `LOCALTIME` вместо `CURRENT_TIMESTAMP` и `CURRENT_TIME` там где вы не хотите получить типы данных с часовыми поясами.
Данные выражения специально были введены в корректирующих релизах Firebird 2.5.9 и Firebird 3.0.4, чтобы вы заранее могли подготовить свои базы данных для миграции на Firebird 4.0.

==== Литералы дат и времени

В Firebird 4.0 ужесточён синтаксис литералов дат и времени.

Литералы 'NOW', 'TODAY', 'TOMORROW', 'YESTERDAY' с неявным приведением типа (с префиксами TIMESTAMP, DATE, TIME) теперь запрещены.
Дело в том, что значение таких литералов оценивалось во время подготовки DSQL запроса или компиляции PSQL модулей, что приводило к неожиданным результатам.

Если что-то вроде TIMESTAMP 'NOW' использовалось в запросах DSQL в коде приложения или в перенесенном PSQL, возникнет проблема совместимости с Firebird 4.

[example]
.Следующий код не будет скомпилирован
====
[listing,subs=+quotes]
----
..
DECLARE VARIABLE moment TIMESTAMP;
..
SELECT TIMESTAMP 'NOW' FROM RDB$DATABASE INTO :moment;

/* здесь переменная: moment будет "заморожена" как отметка времени
в момент последней компиляции процедуры или функции  */
..
----
====

Необходимо вычистить такие литералы (например заменить на явное преобразование типа `CAST('NOW' AS TIMESTAMP)`) в коде ваших процедур и функций до преобразования вашей базы данных в новую ODS.

Кроме того, необходимо проверить другие литералы дат и времени с явным заданием известной даты (времени).
Ранее в таких литералах позволялись разделители частей даты и времени не соответствующие стандарту, теперь такие разделители запрещены.
Подробнее о разрешённых форматах литералов даты и времени вы можете прочитать в "Руководство по языку SQL СУБД Firebird 4.0" в главе "Литералы даты и времени".

=== Внешние функции (UDF) объявлены устаревшими

Поддержка внешней функции (UDF) в Firebird 4 устарела.
Эффект от этого заключается в том, что UDF нельзя использовать с конфигурацией по умолчанию, поскольку для параметра `UdfAccess` в `firebird.conf`
значение по умолчанию теперь `None`.
Библиотеки UDF ib_udf и fbudf изъяты из дистрибутива.

Большинство функций в этих библиотеках уже устарели в предыдущих версиях Firebird и были заменены встроенными аналогами.
Теперь доступны безопасные замены для некоторых из оставшихся функций либо в новой библиотеке определяемых пользователем подпрограмм (UDR) с именем `[lib]udf_compat.[dll/so/dylib]` (это делается после смены ODS), либо в виде преобразований по сценарию в сохраненные функции PSQL.

Рекомендуем заранее (до перехода на новую ODS) заменить UDF функции на их встроенные аналоги.
Если вы делаете миграцию с Firebird 3.0, вы также можете переписать часть функций на PSQL.

Если после этих шагов у вас остались UDF функции, то необходимо изменить параметр конфигурации

[listing,subs=+quotes]
----
UdfAccess = Restrict UDF
----

=== Изменение ODS

После предварительной подготовки, вы можете попробовать изменить ODS с помощью инструмента _gbak_.

В данном примере предполагается, что на одной машине стоят Firebird 3.0 и Firebird 4.0. Firebird 3.0 работает используя TCP порт 3053, а Firebird 4.0 — 3054.

Прежде всего необходимо создать резервную копию вашей базы данных на текущей версии Firebird с помощью следующей команды.

[listing,subs=+quotes]
----
gbak -b -g -V -user <username> -pas <password> -se <service> <database> <backup_file> -Y <log_file>
----

[example]
.Создание резервной копии на текущей версии Firebird
====
[listing,subs=+quotes]
----
gbak -b -g -V -user SYSDBA -pas 8kej712 -se server/3053:service_mgr my_db d:\fb30_backup\my_db.fbk -Y d:\fb30_backup\backup.log
----
====

Далее необходимо восстановить вашу копию на Firebird 4.0 с помощью команды

[listing,subs=+quotes]
----
gbak -c -v -user <username> -pas <password> -se <service> <backup_file> <database_file> -Y <log_file>
----

[example]
.Восстановление резервной копии на Firebird 4.0
====
[listing,subs=+quotes]
----
gbak -c -v -user SYSDBA -pas 8kej712 -se server/3054:service_mgr d:\fb30_backup\my_db.fbk d:\fb40_data\my_db.fdb -Y d:\fb40_data\restore.log
----
====

[IMPORTANT]
.Важно
====
Обратите внимание, на переключатели -V и -Y, они обязательно должны использоваться, чтобы вы могли просмотреть в лог файле, что в процессе восстановления пошло не так.
====

После восстановления внимательно изучите `restore.log` на предмет ошибок. Большая часть из них может происходить по причине
несовместимостей на уровне языка SQL описанных выше. Если вы что-то не исправили, то придётся возвращаться к правке PSQL
объектов в исходной базе данных.


==== Предупреждения об отсутствии UDF

После восстановления в файле `restore.log` вы можете увидеть следующие предупреждения

[listing,subs=+quotes]
----
gbak: WARNING:function UDF_FRAC is not defined
gbak: WARNING: module name or entrypoint could not be found
----

Это означает, что у вас есть UDF, которые объявлены в базе данных, но их библиотека отсутствует.
Выше уже было описано, что надо делать в этом случае. Но это в основном касалось ваших UDF библиотек.
Однако если вы использовали UDF из комплекта поставляемого с Firebird, а именно ib_udf и fbudf, то вы можете
заменить их на встроенные функции или на безопасные аналоги UDR расположенные в библиотеке `udf_compat.dll`.
Для этого необходимо запустить SQL скрипт миграции, поставляемый в комплекте с Firebird 4.0, который
расположен в `misc/upgrade/v4.0/udf_replace.sql`. Это делается следующей командой

[listing,subs=+quotes]
----
isql -user sysdba -pas masterkey -i udf_replace.sql {your-database}
----

[WARINING]
.Предупреждение
====
Этот сценарий не повлияет на объявления UDF из сторонних библиотек!
====

== Перенос псевдонимов баз данных

Этот раздел актуален для тех кто мигрирует с Firebird 2.5.
Файл `aliases.conf` в котором настраивались псевдонимы баз данных переименован в `databases.conf`.
Он полностью обратно совместим по синтаксису, однако его назначение значительно расширено.
Теперь в нём можно задавать некоторые индивидуальные параметры для каждой базы данных, которая описано в нём.
Настоятельно рекомендуем воспользоваться этой возможностью, если ваш сервер обслуживает более 1 базы данных.

Параметры которые можно задавать на уровне базы данных помечены в файле `firebird.conf` надписью 'Per-database configurable'.


== Перенос списка пользователей

Перенос списка пользователей из Firebird 2.5 и Firebird 3.0 осуществляется по-разному. Перенос пользователей из
Firebird 3.0 производится значительно проще, поэтому сначала я опишу этот случай.

=== Перенос списка пользователей из Firebird 3.0

